#----------------------------------------------------------------------------------------------------------------------#

#----------------------------------------------------------------------------------------------------------------------#
server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:postgres://localhost:5432/db_funcionary
    username: postgres
    password: admin
  application:
    name: funcionary-service
  #----------------------------------------------------------------------------------------------------------------------#

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    preferIpAddress: true
    hostName: 192.168.43.77